# THIS FILE IS AUTOMATICALLY GENERATED
# Project: D:\UCU\POC\PSoC_Projects_Embedded\PSoC_LAB1\lab6-psoc-1-shevchuk_lykhanskyi\Lab_2_7SEG.cydsn\Lab_2_7SEG.cyprj
# Date: Tue, 25 Nov 2025 12:16:15 GMT
#set_units -time ns
create_clock -name {CyRouted1} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyWCO} -period 30517.578125 -waveform {0 15258.7890625} [list [get_pins {ClockBlock/wco}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFClk} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyECO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/eco}]]
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFClk} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySysClk} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/sysclk}]]
create_generated_clock -name {SPIM_IntClock} -source [get_pins {ClockBlock/hfclk}] -edges {1 3 7} [list [get_pins {ClockBlock/udb_div_1}]]
create_generated_clock -name {Clock_1} -source [get_pins {ClockBlock/hfclk}] -edges {1 30001 60001} [list [get_pins {ClockBlock/udb_div_3}]]


# Component constraints for D:\UCU\POC\PSoC_Projects_Embedded\PSoC_LAB1\lab6-psoc-1-shevchuk_lykhanskyi\Lab_2_7SEG.cydsn\TopDesign\TopDesign.cysch
# Project: D:\UCU\POC\PSoC_Projects_Embedded\PSoC_LAB1\lab6-psoc-1-shevchuk_lykhanskyi\Lab_2_7SEG.cydsn\Lab_2_7SEG.cyprj
# Date: Tue, 25 Nov 2025 12:16:13 GMT
