# THIS FILE IS AUTOMATICALLY GENERATED
# Project: D:\LABs_BLE\LABs_BLE\Lab_1_LED_PWM.cydsn\Lab_1_LED_PWM.cyprj
# Date: Mon, 24 Nov 2025 14:20:45 GMT
#set_units -time ns
create_clock -name {Clock_1(FFB)} -period 100000 -waveform {0 50000} [list [get_pins {ClockBlock/ff_div_7}]]
create_clock -name {Clock_2(FFB)} -period 100000 -waveform {0 50000} [list [get_pins {ClockBlock/ff_div_10}]]
create_clock -name {CyRouted1} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyWCO} -period 30517.578125 -waveform {0 15258.7890625} [list [get_pins {ClockBlock/wco}]]
create_clock -name {CyLFClk} -period 30517.578125 -waveform {0 15258.7890625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyECO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/eco}]]
create_clock -name {CyIMO} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFClk} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySysClk} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/sysclk}]]
create_generated_clock -name {Clock_1} -source [get_pins {ClockBlock/hfclk}] -edges {1 4801 9601} [list]
create_generated_clock -name {Clock_2} -source [get_pins {ClockBlock/hfclk}] -edges {1 4801 9601} [list]


# Component constraints for D:\LABs_BLE\LABs_BLE\Lab_1_LED_PWM.cydsn\TopDesign\TopDesign.cysch
# Project: D:\LABs_BLE\LABs_BLE\Lab_1_LED_PWM.cydsn\Lab_1_LED_PWM.cyprj
# Date: Mon, 24 Nov 2025 14:20:34 GMT
