# THIS FILE IS AUTOMATICALLY GENERATED
# Project: D:\LABs_BLE\LABs_BLE\Lab_1_1_LED_additional_blue.cydsn\Lab_1_1_LED_additional_blue.cyprj
# Date: Sat, 22 Nov 2025 08:55:28 GMT
#set_units -time ns
create_clock -name {Clock_1(FFB)} -period 333.33333333333331 -waveform {0 166.666666666667} [list [get_pins {ClockBlock/ff_div_7}]]
create_clock -name {CyRouted1} -period 333.33333333333331 -waveform {0 166.666666666667} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyWCO} -period 30517.578125 -waveform {0 15258.7890625} [list [get_pins {ClockBlock/wco}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFCLK} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyECO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/eco}]]
create_clock -name {CyIMO} -period 333.33333333333331 -waveform {0 166.666666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFCLK} -period 333.33333333333331 -waveform {0 166.666666666667} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySYSCLK} -period 333.33333333333331 -waveform {0 166.666666666667} [list [get_pins {ClockBlock/sysclk}]]
create_generated_clock -name {Clock_1} -source [get_pins {ClockBlock/hfclk}] -edges {1 2 3} [list]


# Component constraints for D:\LABs_BLE\LABs_BLE\Lab_1_1_LED_additional_blue.cydsn\TopDesign\TopDesign.cysch
# Project: D:\LABs_BLE\LABs_BLE\Lab_1_1_LED_additional_blue.cydsn\Lab_1_1_LED_additional_blue.cyprj
# Date: Sat, 22 Nov 2025 08:55:27 GMT
